# Generated by Django 2.1.5 on 2019-02-07 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgroFornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.TextField(default='Categoria')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(default='Descrição do Produto')),
                ('atributos', models.FileField(upload_to='data/json')),
                ('imagem', models.FileField(upload_to='data/img')),
                ('fornecedor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AgroFornecedores',
            },
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='novofornecedor',
            options={'verbose_name_plural': 'NovosFornecedores'},
        ),
    ]
