# Generated by Django 2.1.5 on 2019-01-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='descricao',
            field=models.TextField(default='Descrição do Produto'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='id_ctgr',
            field=models.PositiveSmallIntegerField(default=99),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='id_frncdr',
            field=models.PositiveSmallIntegerField(default=89),
            preserve_default=False,
        ),
    ]
