# Generated by Django 2.1.5 on 2019-01-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_auto_20190113_1659'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categorias',
        ),
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name_plural': 'Categorias'},
        ),
    ]
