# Generated by Django 2.1.5 on 2019-01-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_auto_20190113_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='atributos',
            field=models.FileField(upload_to='json'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.FileField(upload_to='img'),
        ),
    ]
