# Generated by Django 2.1.5 on 2019-01-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_auto_20190113_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='atributos',
            field=models.FileField(upload_to='data/json'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.FileField(upload_to='data/img'),
        ),
    ]
