# Generated by Django 2.1.5 on 2019-01-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_auto_20190113_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='id_ctgr',
        ),
        migrations.AddField(
            model_name='produtos',
            name='categoria',
            field=models.TextField(default='Categoria'),
        ),
    ]
