# Generated by Django 2.1.5 on 2019-02-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_produtos_fornecedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='id_frncdr',
        ),
    ]
