# Generated by Django 2.1.5 on 2019-01-27 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, max_length=7)),
                ('rua', models.TextField(blank=True, max_length=200)),
                ('bairro', models.TextField(blank=True, max_length=50)),
                ('cidade', models.TextField(blank=True, max_length=50)),
                ('estado', models.TextField(blank=True, max_length=50)),
                ('complemento', models.TextField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
