# Generated by Django 2.1.5 on 2019-01-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190127_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
