# Generated by Django 2.1.5 on 2019-02-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190205_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
